kind: Pod
apiVersion: v1
metadata:
  name: labels
  labels:
    course: k8
    trainer: sivakumar
  annotations:
    kubernetes.io/created-by: "AkshayKumar"
    jenkins.build.url: 'https://jenkins.akshaydaws-78s.online/expense/job/backend/54'
spec:
  containers:
  - name: nginx
    image: nginx