kind: Deployment
apiVersion: app/v1
metadata:
  name: nginx
  # these labels belongs to deployment resource
  labels:
    app: nginx
    purpose: deployment
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      tier: web
      app: nginx
      project: test-project
  # below is pod definition
  template:
    metadata:
      labels:
        tier: web
        app: nginx
        project: test-project
    spec:
      containers:
      - name: nginx
        image: nginx